version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn test -Pstart-dynamodb-local &
      - mvn test -P${PROFILE} -Ddynamodb-partitions=1 -Ddynamodb-control-plane-rate=10000 -Ddynamodb-unlimited-iops=true -Dproperties-file=src/test/resources/dynamodb-local.properties
      - mvn surefire-report:report -pl $MODULE
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/**/*
